In [100]:
import torch

In [101]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
a.shape, a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

In [103]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

`view()` 方法可以用来改变一个张量的形状.

In [104]:
(id(a.storage()), id(b.storage()))

(140128885884816, 140128885957136)

In [105]:
a.storage() is b.storage()

False

In [106]:
id(a.storage()) == id(b.storage())

False

In [107]:
a_clone = a.clone()
b_clone = a_clone.view(3, 3)

b_clone[1, 1] = 9
a_clone, b_clone

(tensor([0, 1, 2, 3, 9, 5, 6, 7, 8]),
 tensor([[0, 1, 2],
         [3, 9, 5],
         [6, 7, 8]]))

In [108]:
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [109]:
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

👆

因为对于 `c`, 它仍在 `b` 和 `a` 的内存中, 所以 `c` 的步长的计算应该是以 `b` 和 `a` 的形状为基础的.