# 1. tensors

In [1]:
a = [1.0, 2.0, 1.0]
a   # 此时的a是一个list

[1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch
a = torch.ones(3)
a   # 此时的a不再是和之前一样的list而是一个张量了

tensor([1., 1., 1.])

👆

此张量是一个1维张量, 长度为3.

如果想要一个二维张量则 `torch.ones(3, 3)`, 同理, 如果想要一个3为则 `torch.ones(3, 3, 3)`

In [5]:
# 查看数据类型
print(type(a[1]))
a[1]

<class 'torch.Tensor'>


tensor(1.)

👆

注意, 这里的`a`的 type 并不能用于简单计算

为此, 我们要将其转换为`float`

👇

In [6]:
float(a[1])

1.0

In [7]:
# 修改张量中的值

a[2] = 2.  # 值得注意的是, 这里可以是`= 2.`也可以是更规范的`2.0`
a

tensor([1., 1., 2.])

In [8]:
# 生成一个长度为6的1维的数值全部都是0的张量
points = torch.zeros(6)

# 对单个数值进行修改
points[0] = 4.
points[1] = 1.
points[2] = 5.
points[3] = 3.
points[4] = 2.
points[5] = 1.
points

tensor([4., 1., 5., 3., 2., 1.])

👆

同样的结果, 但是更简单的方法

👇

In [9]:
points = torch.tensor([4., 1., 5., 3., 2., 1.])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

建立一个`3*2`的一个二维张量

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

如果要取出其中一个元素就需要两个元素来进行指定了

👇

In [13]:
points[0, 0]

tensor(4.)