# Data types

- torch.float32 or torch.float: 32-bit floating-point
- torch.float64 or torch.double: 64-bit, double-precision floating-point
- torch.float16 or torch.half: 16-bit, half-precision floating-point
- torch.int8: signed 8-bit integers
- torch.uint8: unsigned 8-bit integers
- torch.int16 or torch.short: signed 16-bit integers
- torch.int32 or torch.int: signed 32-bit integers
- torch.int64 or torch.long: signed 64-bit integers
- torch.bool: Boolean

> 数据类型与内存占用直接相关. 用int32会爆内存的换成uint8等可能就可以正常运行了.

In [3]:
import torch

In [4]:
double_points = torch.ones(10, 2, dtype=torch.double)

short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [6]:
double_points, short_points

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]], dtype=torch.float64),
 tensor([[1, 2],
         [3, 4]], dtype=torch.int16))

In [5]:
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [7]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [8]:
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

In [9]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [10]:
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

In [26]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.short()
print(points_64)
print(points_short)

tensor([0.3774, 0.0838, 0.6831, 0.8665, 0.0912], dtype=torch.float64)
tensor([0, 0, 0, 0, 0], dtype=torch.int16)


👆

`.short()` 并没有取四舍五入, 而是直接取其整数部分.

```python
>>> torch.tensor([12.3]).short()
tensor([12], dtype=torch.int16)
>>> torch.tensor([12.7]).short()
tensor([12], dtype=torch.int16)
```

相当于 numpy 中的 `np.floor()`

In [28]:
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

👆

其存放是按照 `torch.float64` 来存放的, 也就是按照内存占用最大的来存放的.