# 4.

In [3]:
import torch

In [4]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [5]:
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:8]    # 注意是可以超过列表的大小的, 虽然结果到不了8, 但是不会报错而是直接取到 `5`
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

some_list[:4]    # <4>

[0, 1, 2, 3]

```python
>>> some_list[:]
[0, 1, 2, 3, 4, 5] # <1>
>>> some_list[1:4]
[1, 2, 3, 4]       # <2>
>>> some_list[1:]
[1, 2, 3, 4, 5]    # <3>
>>> some_list[:4]
[0, 1, 2, 3]       # <4>
>>> some_list[:8]
[0, 1, 2, 3, 4, 5] # <5>
>>> some_list[:-1]
[0, 1, 2, 3, 4]    # <6>
>>> some_list[1:4:2]
[1, 3]             # <7>
```

- <4>: 包含索引为4的元素
- <5>: 注意是可以超过列表的大小的, 虽然结果到不了8, 但是不会报错而是直接取到 `5`
- <6>: 负数索引表示从列表尾部开始计数, 但是不取到索引的元素
- <7>: 第三个参数表示步长, 从索引1开始, 每隔2个元素取一个, 即步长为2

In [7]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [8]:
points[1]

tensor([5., 3.])

In [9]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [10]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [11]:
points[1:, 0]

tensor([5., 2.])

In [14]:
a = points[None]
b = torch.unsqueeze(points, 0)
print(a.shape, b.shape)
a == b, a.shape == b.shape

torch.Size([1, 3, 2]) torch.Size([1, 3, 2])


(tensor([[[True, True],
          [True, True],
          [True, True]]]),
 True)

👆

对于 `point[None]`, 其和 `unsqeeze` 的作用是一样的, 即增加一个维度

---

从 `torch` 变成 `numpy`

👇


In [16]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

从 `numpy` 变成 `torch`

👇


In [17]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])