# Files' IO

In [1]:
import torch
points = torch.ones(3, 4)

## 写文件

In [2]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [3]:
# 用 python 的模式

with open('../data/p1ch3/ourpoints.t', 'wb') as f:
    torch.save(points, f)

👆

`open` 函数中的 `wb` 参数表示以二进制写入的方式打开文件

| Mode |	Description |
| --- | --- |
| `r` |	Open a file for reading. (default) |
| `w` |	Open a file for writing. Creates a new file if it does not exist or truncates the file if it exists. |
| `x` |	Open a file for exclusive creation. If the file already exists, the operation fails. |
| `a` |	Open for appending at the end of the file without truncating it. Creates a new file if it does not exist. |
| `t` |	Open in text mode. (default) |
| `b` |	Open in binary mode. |
| `+` |	Open a file for updating (reading and writing) |

中文 👇

| 模式 |	描述 |
| --- | --- |
| `r` |	打开一个文件进行读取。（默认） |
| `w` |	打开一个文件进行写入。如果文件不存在则创建新文件，如果文件存在则清空文件。 |
| `x` |	独占方式创建一个文件。如果文件已存在，则操作失败。 |
| `a` |	在文件末尾追加内容，不会清空文件。如果文件不存在则创建新文件。 |
| `t` |	以文本模式打开。（默认） |
| `b` |	以二进制模式打开。 |
| `+` |	打开一个文件进行更新（读取和写入）

## 读文件

In [4]:
a = torch.load('../data/p1ch3/ourpoints.t')
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
with open('../data/p1ch3/ourpoints.t', 'rb') as f:
    a = torch.load(f)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## h5py

In [6]:
import h5py

In [7]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data = points.numpy())
f.close()

👆

这段代码是使用h5py库来创建一个HDF5文件，并在其中存储数据。

具体来说：

1. `f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')`：这行代码创建了一个HDF5文件，文件路径是'../data/p1ch3/ourpoints.hdf5'，并且以写入模式（'w'）打开这个文件。如果文件已经存在，它将被清空；如果文件不存在，将创建新文件。

2. `dset = f.create_dataset('coords', data = points.numpy())`：这行代码在HDF5文件中创建了一个名为'coords'的数据集，并将`points.numpy()`的数据存储在这个数据集中。`points.numpy()`是将PyTorch张量转换为NumPy数组。

3. `f.close()`：这行代码关闭了HDF5文件。在完成所有的读写操作后，应该关闭文件以释放系统资源。

HDF5是一种存储大规模科学数组数据的文件格式，它可以让你存储大量的数值数据，并且可以高效地被Python或其他语言的程序读取。

In [8]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
dset

<HDF5 dataset "coords": shape (3, 4), type "<f4">

In [10]:
last_points = dset[:]
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [11]:
# 由上可见是numpy.array的形式, 转成tensor

last_points = torch.from_numpy(dset[:])
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
# 也可以
last_points = torch.tensor(dset[:])
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
f.close()

👆

注意要将其关闭, 以释放系统资源.

## 打开文件在 GPU

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points + points_gpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [15]:
points = points.cuda()
points + points_gpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:0')